<?xml version="1.0"?>
<!DOCTYPE challengedata
[

<!ELEMENT challengedata (job)*>

<!ELEMENT job (challengeinfo)+>
<!ATTLIST job 
  code CDATA #REQUIRED
>

<!ELEMENT challengeinfo (klass,param*,value?,curr?)>
<!ATTLIST challengeinfo
  spec CDATA #REQUIRED
>

<!ELEMENT klass (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT curr  (#PCDATA)>

]>

<challengedata>
    <!-- beim Versenden eines Jobs müssen u.U. eine Challenge-Klasse, Challenge-
         Parameter sowie evtl. auch ein Challenge-Wert übertragen werden.
         
         Für die Zuordnung der Jobs zu den Challenge-Klassen und den jeweils
         benötigten Parametern könnte es unterschiedliche Spezifikationen
         geben (im Moment ist nur HHD-1.2 bekannt).
         
         Hier wird nun für jeden Job definiert, welche Challenge-Klasse zu
         diesem Job gehört und wie der Pfad zu dem (den) Datenelement(en)
         lautet, die die jeweils benötigten Challenge-Parameter enthalten.
         Außerdem wird der Pfad zum Challenge-Wert und zur -Währung definiert.
         
         Das ganze jeweils für jede Spezifikation separat.
    -->

    <job code="DKTAZ">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKAOM">
        <challengeinfo spec="hhd12">
            <klass>20</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKAUE">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKAZK">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKCCS">
        <challengeinfo spec="hhd12">
            <klass>22</klass>
            <param>Other.iban</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKDAB">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKDAE">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKDAL">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKDAN">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKDTE">
        <challengeinfo spec="hhd12">
            <klass>50</klass>
            <param>sumOthers</param>
            <value>sumValue</value>
            <curr>sumCurr</curr>
        </challengeinfo>
    </job>

    <job code="HKEIL">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKEKA">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKFGB">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKFGK">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKFGN">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Belastungskto.number</param>
            <value>Anlagebetrag.value</value>
            <curr>Anlagebetrag.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKGUB">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKINF">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKLAS">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKLSW">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKKAN">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKKAZ">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKKDM">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKKIA">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKKIF">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKKOM">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKPAE">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKPRO">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKSAL">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKSLA">
        <challengeinfo spec="hhd12">
            <klass>50</klass>
            <param>sumOthers</param>
            <value>sumValue</value>
            <curr>sumCurr</curr>
        </challengeinfo>
    </job>

    <job code="HKSLB">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKSLE">
        <challengeinfo spec="hhd12">
            <klass>50</klass>
            <param>sumOthers</param>
            <value>sumValue</value>
            <curr>sumCurr</curr>
        </challengeinfo>
    </job>

    <job code="HKSLL">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKSUB">
        <challengeinfo spec="hhd12">
            <klass>50</klass>
            <param>sumOthers</param>
            <value>sumValue</value>
            <curr>sumCurr</curr>
        </challengeinfo>
    </job>

    <job code="HKTAZ">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKTSB">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKTSE">
        <challengeinfo spec="hhd12">
            <klass>50</klass>
            <param>sumOthers</param>
            <value>sumValue</value>
            <curr>sumCurr</curr>
        </challengeinfo>
    </job>

    <job code="HKTSL">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKTUA">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKTUB">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKTUE">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKTUL">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKUEB">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKUMB">
        <challengeinfo spec="hhd12">
            <klass>10</klass>
            <param>Other.number</param>
            <value>BTG.value</value>
            <curr>BTG.curr</curr>
        </challengeinfo>
    </job>

    <job code="HKWDU">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKWPD">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKWPI">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKWPK">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKWPR">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>

    <job code="HKWSD">
        <challengeinfo spec="hhd12">
            <klass>90</klass>
        </challengeinfo>
    </job>
</challengedata>
